spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book-service/**